# graphRAG/config/vector_store_config.yml

vector_store:
  type: "faiss"  
  tool_embeddings_path: "agents/embeddings/galaxy_embeddings_20251009_155152.npy"
  tool_metadata_path: "agents/embeddings/galaxy_metadata_20251009_155152.json"
  workflow_embeddings_path: "agents/embeddings/iwc_workflow_embeddings_20251006_113552.npy"
  workflow_metadata_path: "agents/embeddings/iwc_workflow_metadata_20251006_113552.json"
  top_k: 5
