# -------------------
# Relationships
# -------------------
relationships:
  Workflow_CATEGORY:
    from: Workflow
    to: Category
    type: BELONGS_TO
    fields: []

  Tool_CATEGORY:
    from: Tool
    to: ToolCategory
    type: BELONGS_TO
    fields: []

  Workflow_STEP:
    from: Workflow
    to: Step
    type: HAS_STEP
    fields: []

  Workflow_IMPLEMENTATION:
    from: Workflow
    to: Workflow
    type: HAS_IMPLEMENTATION
    fields: []

  Step_TOOL:
    from: Step
    to: Tool
    type: USES_TOOL
    fields: []

  Step_INPUT:
    from: Step
    to: ToolInput
    type: STEP_REQUIRES
    fields: []

  Step_OUTPUT:
    from: Step
    to: ToolOutput
    type: STEP_GENERATES
    fields: []

  Workflow_KEYWORD:
    from: Workflow
    to: Keyword
    type: HAS_KEYWORD
    fields: []

  Workflow_WorkflowInput:
    from: Workflow
    to: WorkflowInput
    type: HAS_INPUT
    fields: []

  Workflow_WorkflowOutput:
    from: Workflow
    to: WorkflowOutput
    type: HAS_OUTPUT
    fields: []

  Tool_INPUT:
    from: Tool
    to: ToolInput
    type: HAS_INPUT
    fields: []

  Tool_OUTPUT:
    from: Tool
    to: ToolOutput
    type: HAS_OUTPUT
    fields: []

  Tool_KEYWORD:
    from: Tool
    to: Keyword
    type: HAS_KEYWORD
    fields: []

  Tool_SIMILAR:
    from: Tool
    to: Tool
    type: SIMILAR_TO
    fields:
      - score   # float similarity score