WorkflowTOOL:
  label: USES_TOOL
  source: Workflow
  target: Tool
  properties: {}   # none yet

WorkflowCategory:
  label: BELONGS_TO
  source: Workflow
  target: Category

ToolCategory:
  label: BELONGS_TO
  source: Tool
  target: Category

WorkflowInput:
  label: HAS_INPUT
  source: Workflow
  target: Input

WorkflowOutput:
  label: HAS_OUTPUT
  source: Workflow
  target: Output

WorkflowKeyword:
  label: HAS_KEYWORD
  source: Workflow
  target: Keyword

ToolKeyword:
  label: HAS_KEYWORD
  source: Tool
  target: Keyword

ToolSimilar:
  label: SIMILAR_TO
  source: Tool
  target: Tool
  properties:
    score: {type: float}