import os
import logging
from dotenv import load_dotenv
import google.generativeai as genai
import openai

# ------------------ CONFIGURATION ------------------ #
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Check environment variables
if not GEMINI_API_KEY and not OPENAI_API_KEY:
    raise ValueError(" Both GEMINI_API_KEY and OPENAI_API_KEY are missing in .env — please provide at least one.")

# Prioritize OpenAI if both are available
DEFAULT_PROVIDER = "openai" if OPENAI_API_KEY else "gemini"
logger.info(f"✅ Using {DEFAULT_PROVIDER.upper()} as default LLM provider.")


# ------------------ LLM WRAPPERS ------------------ #
class LLMInterface:
    """Base class for LLM wrappers."""
    def generate(self, prompt: str) -> str:
        raise NotImplementedError("Subclasses must implement 'generate' method.")


class GeminiModel(LLMInterface):
    def __init__(self, api_key: str, model_name: str = "models/gemini-2.5-flash"):
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel(model_name)

    def generate(self, prompt: str) -> str:
        response = self.model.generate_content(prompt)
        return response.text.strip()


class OpenAIModel(LLMInterface):
    def __init__(self, api_key: str, model_name: str = "gpt-4o-mini"):
        openai.api_key = api_key
        self.model_name = model_name

    def generate(self, prompt: str) -> str:
        response = openai.chat.completions.create(
            model=self.model_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=1200
        )
        return response.choices[0].message.content.strip()


# ------------------ PROVIDER SELECTION ------------------ #
def get_llm(provider: str = None) -> LLMInterface:
    """Selects the appropriate LLM provider with fallbacks."""
    provider = (provider or DEFAULT_PROVIDER).lower()

    if provider == "openai":
        if not OPENAI_API_KEY:
            if GEMINI_API_KEY:
                logger.warning(" OpenAI API key missing — falling back to Gemini.")
                return GeminiModel(GEMINI_API_KEY)
            raise ValueError(" OpenAI API key missing, and no Gemini fallback available.")
        return OpenAIModel(OPENAI_API_KEY)

    elif provider == "gemini":
        if not GEMINI_API_KEY:
            if OPENAI_API_KEY:
                logger.warning("Gemini API key missing — falling back to OpenAI.")
                return OpenAIModel(OPENAI_API_KEY)
            raise ValueError("Gemini API key missing, and no OpenAI fallback available.")
        return GeminiModel(GEMINI_API_KEY)

    else:
        raise ValueError("Invalid provider name — choose 'openai' or 'gemini'.")


# ------------------ INITIALIZE MODEL ------------------ #
llm = get_llm()


# ------------------ SUMMARIZATION FUNCTIONS ------------------ #
def summarize_tool_suggestions(tools: list, query: str) -> str:
    """Summarizes and ranks tool suggestions using the selected LLM."""
    tool_descriptions = "\n\n".join(
        f"{i+1}. {tool['name']} (Category: {tool['category']})\n"
        f"{tool['description'] or 'No description provided.'}"
        for i, tool in enumerate(tools)
    )

    prompt = f"""
You are a helpful AI assistant for Galaxy bioinformatics tools.

A user asked: "{query}"

Start your response with **"Ranked Suggested Tools"** — make it bold and clear.
Present the tools in a numbered list ordered by relevance score.
Be concise and confident (the data is generated by the E5 model).

{tool_descriptions}

Now write a natural, friendly, and ranked summary recommending these tools.
Briefly explain what each tool is suitable for.
"""

    return llm.generate(prompt)


def summarize_workflow_suggestions(workflows: list, query: str) -> str:
    """Summarizes and ranks workflow suggestions using the selected LLM."""
    workflow_descriptions = "\n\n".join(
        f"{i+1}. {wf['name']} (Category: {wf['category']}, Score: {wf['score']:.2f})\n"
        f"{wf['readme_excerpt'] or 'No details provided.'}"
        for i, wf in enumerate(workflows)
    )

    prompt = f"""
You are a helpful AI assistant for Galaxy workflows.

A user asked: "{query}"

Start with **"Ranked Workflows in Galaxy"** — make it bold and clear.
List workflows in numbered order with short, confident descriptions.
Their order reflects their score (higher = more relevant).

{workflow_descriptions}

Now write a clear and friendly summary describing what each workflow does.
"""

    return llm.generate(prompt)
